### ISSUE TITLE
Bug真多 没有测试过的吧？

### ISSUE THREAD

**Issue by 995933447** [mojisrc/fashop-admin#12]

**Comment by 995933447** [comment]
Cannot read property 'map' of undefined
PhotoGallery._this.goodsImgList [as render]

**Comment by 995933447** [comment]
src/components/public/photoGallery/index.js:266

**Comment by wangxingkang** [comment]
毕竟是开源项目 有问题 可以直接PR

**Comment by TELstatic** [comment]
吐槽一下 命名看着是真的难受

**Comment by hanwenbo** [comment]
更新了一版  在几十个客户上测试过了 先关了 铁子 有问题再反馈吧
