### ISSUE TITLE
npm run build 的问题

### ISSUE THREAD

**Issue by 3340971** [mojisrc/fashop-admin#13]
执行build的时候到90%多突然就killed，没有任何错误提示，如下

[root@development fashop-admin]# npm run build

> fashop-admin@2.0.0 build /home/www/fashop-admin
> umi build

● Webpack █████████████████████████ additional chunk assets processing (91%)

Killed

**Comment by hanwenbo** [comment]
和项目无关，可能你的环境没符合umi的要求

**Comment by hanwenbo** [comment]
尝试对照umi文档环境再配置一下

**Comment by wangxingkang** [comment]
应该是umi的问题 可以提个issue给umi

**Comment by wangxingkang** [comment]
先关闭
