### ISSUE TITLE
建议建立一个fashop的组织，放置fashop相关的项目

### ISSUE THREAD

**Issue by wangxingkang** [mojisrc/fashop-admin#4]

**Comment by hanwenbo** [comment]
fashop那个名字被占用了 有解决的办法没  现在组织叫mojisrc

**Comment by wangxingkang** [comment]
fashop-home  fashop-workspace  可以起个这样的

**Comment by hanwenbo** [comment]
@wangxingkang 我联系下官方看看是否能把那个空白账号清理下

**Comment by wangxingkang** [comment]
哈哈 那样最好

**Comment by hanwenbo** [comment]
@wangxingkang 还正在联系，他们刚发来邮件  让提供个商标  明天处理下  还不确定是否能用fashop 把那个账号解除

**Comment by wangxingkang** [comment]
哈哈 这个不着急

**Comment by wangxingkang** [comment]
@hanwenbo 要不要建个钉钉群

**Comment by wangxingkang** [comment]
群号 23123420 钉钉现在在企业用的比较多

**Comment by hanwenbo** [comment]
![image](https://user-images.githubusercontent.com/5869741/50675199-6d98a500-1027-11e9-83c2-8fadec3e24cc.png)
@wangxingkang  进来下
